name = "piefayth/aikenblog1"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'piefayth/aikenblog1'"

[repository]
user = "piefayth"
project = "aikenblog1"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
